#!/bin/sh

rm -f /etc/issue
rm -f /etc/motd
rm -f /etc/update-motd.d/10-uname

mv /etc/hbs-issue /etc/issue || true
mv /etc/hbs-motd /etc/motd || true
mv /etc/update-motd.d/hbs-uname /etc/update-motd.d/10-uname || true
