#!/bin/bash

COUNT=0

version() {
    case $1 in
        nodesource )  echo `node -e 'console.log(require("./package.json").engines.nodesource)'`
                      ;;

        * )           echo `node -e 'console.log(require("./package.json").version)'`
                      ;;
    esac
}

image() {
    VERSION=`project version`

    if [[ -f "builds/$1-v$VERSION-$2.xz" ]]; then
        echo "$1-$VERSION-$2 up to date"
    else
        if [[ $COUNT -gt 0 ]] ; then
            echo "" >> build.log
        fi

        echo "$1 - $2 - $(date)" >> build.log
        echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

        make $1-version-$2.img.xz.sha256

        echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

        COUNT=$((COUNT+1))
    fi
}

build() {
    touch build.log
    truncate -s 0 build.log

    case $1 in
        box )     image "hoobs-box" "arm64"
                  ;;

        card )    image "hoobs" "arm64"
                  ;;

        legacy )  image "hoobs" "armhf"
                  ;;

        * )       image "hoobs-box" "arm64"
                  image "hoobs" "arm64"
                  image "hoobs" "armhf"
                  ;;
    esac
}

rebuild() {
    make clean
    build
}

case $1 in
    version )  version $2
               ;;

    build )    build $2
               ;;

    rebuild )  rebuild
               ;;

    clean )    make clean
               ;;

    * )        ;;
esac
