#!/bin/bash

COUNT=0

version() {
    echo `node -e 'console.log(require("./package.json").version)'`
}

image() {
    if [[ $COUNT -gt 0 ]] ; then
        echo "" >> build.log
    fi

    echo "$1 - $2 - $(date)" >> build.log
    echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

    make $1-version-$2.img.xz.sha256

    echo "------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" >> build.log

    COUNT=$((COUNT+1))
}

build() {
    touch build.log
    truncate -s 0 build.log

    image "hoobs-box" "arm64"
    image "hoobs" "arm64"
}

rebuild() {
    make clean
    build
}

case $1 in
    version )  version
               ;;

    build )    build
               ;;

    rebuild )  rebuild
               ;;

    clean )    make clean
               ;;

    * )        ;;
esac
