#!/usr/bin/env node

/**************************************************************************************************
 * hoobs-image                                                                                    *
 * Copyright (C) 2021 HOOBS                                                                       *
 *                                                                                                *
 * This program is free software: you can redistribute it and/or modify                           *
 * it under the terms of the GNU General Public License as published by                           *
 * the Free Software Foundation, either version 3 of the License, or                              *
 * (at your option) any later version.                                                            *
 *                                                                                                *
 * This program is distributed in the hope that it will be useful,                                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                                 *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                  *
 * GNU General Public License for more details.                                                   *
 *                                                                                                *
 * You should have received a copy of the GNU General Public License                              *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.                          *
 **************************************************************************************************/

const Program = require("commander");
const Request = require("axios");
const { join } = require("path");
const { readFileSync } = require("fs");
const { execSync } = require("child_process");
const { MongoClient } = require("mongodb");
const credentials = require("../security/credentials.json");

const pjson = JSON.parse(readFileSync(join(__dirname, "package.json")).toString());

function execLocal(command, options) {
    try {
        return execSync(command, options || { cwd: __dirname, stdio: "inherit" }).toString().trim();
    } catch (_error) {
        return "";
    }
}

function createRelease(title, notes, beta) {
    if (beta) {
        execLocal(`gh release create v${pjson.version} ${join(__dirname, "builds", `hoobs*-v${pjson.version}-*.*`)} -p -t '${title} ${pjson.version}' -n '${notes}'`, { cwd: __dirname, stdio: "inherit" });
    } else {
        execLocal(`gh release create v${pjson.version} ${join(__dirname, "builds", `hoobs*-v${pjson.version}-*.*`)} -t '${title} ${pjson.version}' -n '${notes}'`, { cwd: __dirname, stdio: "inherit" });
    }
}

Program.version(pjson.version, "-v, --version", "output the current version");
Program.allowUnknownOption();

Program.command("repository <branch>")
    .description("fetch versions from live repository")
    .action(async (branch) => {
        const packages = ((await Request.get(`https://dl.hoobs.org/debian/dists/${branch}/main/binary-amd64/Packages`)).data || "").split("\n");
        const results = [];

        for (let i = 0; i < packages.length; i += 1) {
            if (packages[i].startsWith("Package:")) results.push(packages[i].split(":").pop().trim());
            if (packages[i].startsWith("Version:")) results.push(packages[i].split(":").pop().trim());
        }

        console.log(results.join(" "));
        process.exit();
    });

Program.command("released <branch>")
    .description("fetch the current released version")
    .action(async (branch) => {
        const release = (((await Request.get(`https://support.hoobs.org/api/releases/image/${branch === "edge" ? "beta" : "latest"}`)).data) || {}).results;

        console.log(release.version);
        process.exit();
    });

Program.command("edge")
    .description("publish hoobs desktop")
    .action(async () => {
        const client = new MongoClient(credentials.db, { useUnifiedTopology: true });

        await client.connect();

        const database = client.db("support");
        const releases = database.collection("releases");

        createRelease("HOOBS", "HOOBS image for Raspberry Pi.\n\n* Big fixes", true);

        await releases.updateMany({ application: "image", latest: true, beta: true }, { $set: { latest: false } });
        await releases.updateMany({ application: "server", latest: true, beta: true }, { $set: { latest: false } });
        await releases.updateMany({ application: "box", latest: true, beta: true }, { $set: { latest: false } });

        await releases.deleteMany({ application: "image", version: pjson.version, beta: true });
        await releases.deleteMany({ application: "server", version: pjson.version, beta: true });
        await releases.deleteMany({ application: "box", version: pjson.version, beta: true });

        await releases.insertOne({
            application: "image",
            version: pjson.version,
            published: new Date(),
            latest: true,
            download_box: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-box-v${pjson.version}-armhf.xz`,
            download_armhf: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-v${pjson.version}-armhf.xz`,
            download_arm64: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-v${pjson.version}-arm64.xz`,
            beta: true,
        });

        process.exit();
    });

Program.command("stable")
    .description("publish hoobs desktop")
    .action(async () => {
        const client = new MongoClient(credentials.db, { useUnifiedTopology: true });

        await client.connect();

        const database = client.db("support");
        const releases = database.collection("releases");

        createRelease("HOOBS", "HOOBS image for Raspberry Pi.\n\n* Big fixes", false);

        await releases.updateMany({ application: "image", latest: true, beta: false }, { $set: { latest: false } });
        await releases.updateMany({ application: "server", latest: true, beta: false }, { $set: { latest: false } });
        await releases.updateMany({ application: "box", latest: true, beta: false }, { $set: { latest: false } });

        await releases.deleteMany({ application: "image", version: pjson.version, beta: false });
        await releases.deleteMany({ application: "server", version: pjson.version, beta: false });
        await releases.deleteMany({ application: "box", version: pjson.version, beta: false });

        await releases.insertOne({
            application: "image",
            version: pjson.version,
            published: new Date(),
            latest: true,
            download_box: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-box-v${pjson.version}-armhf.xz`,
            download_armhf: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-v${pjson.version}-armhf.xz`,
            download_arm64: `https://github.com/hoobs-org/image/releases/download/v${pjson.version}/hoobs-v${pjson.version}-arm64.xz`,
            beta: false,
        });

        process.exit();
    });

Program.parse(process.argv);
