#!/bin/sh

set -e

PREREQS=""

case $1 in
    prereqs) echo "$PREREQS"; exit 0;;
esac

. /scripts/functions

rootpart=$(realpath $ROOT)
rootpart_nr=$(blkid -sPART_ENTRY_NUMBER -o value -p $rootpart)
rootdev="/dev/$(lsblk -no pkname "$rootpart")"

parted -s $rootdev print 2>&1 | grep -z "fix the GPT" && {
    echo "Fix" | parted ---pretend-input-tty $rootdev print
}

free_space="$(parted -m -s $rootdev print free | tail -n1 | grep free)"

if test -z "$free_space"; then
    exit 0
fi

log_begin_msg "$0 resizing $ROOT"

umount "${rootmnt}"
parted -s $rootdev resizepart $rootpart_nr 100%

wait_for_udev 5

partprobe $rootdev
resize2fs $rootpart

if ! mount -r ${FSTYPE:+-t "${FSTYPE}"} ${ROOTFLAGS} "${ROOT}" "${rootmnt?}"; then
    panic "Failed to mount ${ROOT} as root file system."
fi

log_end_msg
