#!/bin/bash

printf "\n"
printf "     __  ______  ____  ____ _____ "
printf "    / / / / __ \/ __ \/ __ ) ___/ "
printf "   / /_/ / / / / / / / __  \__ \  "
printf "  / __  / /_/ / /_/ / /_/ /__/ /  "
printf " /_/ /_/\____/\____/_____/____/   "
printf "                                  "
printf "\n"
