#!/bin/bash

printf "\n"
printf "     __  ______  ____  ____ _____ \n"
printf "    / / / / __ \/ __ \/ __ ) ___/ \n"
printf "   / /_/ / / / / / / / __  \__ \  \n"
printf "  / __  / /_/ / /_/ / /_/ /__/ /  \n"
printf " /_/ /_/\____/\____/_____/____/   \n"
printf "                                  \n"
printf "\n"
