#!/bin/bash

IP=$(hostname -I)

printf "To configure HOOBS browse to the one of the following addresses from another device on your network:" | fold -s
printf "\n\n"
printf "  http://$(hostname)\n"
printf "  http://$(hostname).local\n"

for ip in $IP; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf "  http://$ip\n"
  else
    printf "  http://[$ip]\n"
  fi
done
