#!/bin/sh
set -e

PREREQS=""

case $1 in
    prereqs) echo "$PREREQS"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/blkid
copy_exec /bin/lsblk
copy_exec /sbin/parted
copy_exec /sbin/partprobe
copy_exec /sbin/resize2fs
